### ISSUE TITLE
Influx disappeared after update to 2.0 on Mac

### ISSUE THREAD

**Issue by Kullenej** [jensmtg/influx#25]
At least for me, it seemed like influx is not showing up on any pages. It is turned on in the settings. I have also restarted Obsidian several times. Before 2.0 it worked just fine.

**Comment by jensmtg** [comment]
With the new version by default it is not shown, if there are no mentions to show. I see that I could include an option for this.
Do you not see the component even in pages with mentions?

**Comment by cakechaser** [comment]
I have the same issue on MacOS, it's not shown on any of the pages, even if there are mentions.

**Comment by Kullenej** [comment]
Today when I opened up Obsidian, Influx suddenly appeared on pages again. For my part, this issue is done.

**Comment by jensmtg** [comment]
> For me it seems to be randomly either working or not. Right now it's not working and I get the following error in the console: <img alt="image" width="522" src="https://user-images.githubusercontent.com/16690476/196277372-70cbf361-daa0-4784-b4ef-3612b7401f2f.png">
> 
> I don't have the data.json file in the plugin folder, I guess I didn't change any settings and it was not generated.

That's interesting. I suspect there's a bug that surfaces due to something about the formatting of the notes with mentions. I understand if you cannot provide the notes themselves, but I think it's hard to find the bug unless you can maybe experiment with the notes with mentions to see exactly what part of the note that causes the bug...
